name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]  # Update to recent versions

    steps:
    - uses: actions/checkout@v3  # Update to the latest version
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Update to the latest version
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test

